# Site settings
title: SiteGo
brand_image: /images/logo_small.png
email: support@sitego.co
description: >- # this means to ignore newlines until "baseurl:"
  SiteGo builds open source communication and collaboration tools for Office 365 which boost productivity and help you connect with the most important people in your business: your employees and customers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sitego.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: readysitego
github_username: readysitego

# Blog Config
show_excerpts: true

# Build settings
markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-gist
 - jekyll-paginate
 - jekyll-seo-tag

exclude: [vendor, node_modules]
